cleos create account eosio bob EOS5apmi5ksicQydemG6rCT9XVt6ToRpQLWCZeMBiHXVrmEvmxRty
cleos create account eosio alice EOS5apmi5ksicQydemG6rCT9XVt6ToRpQLWCZeMBiHXVrmEvmxRty
cleos create account eosio chess EOS5apmi5ksicQydemG6rCT9XVt6ToRpQLWCZeMBiHXVrmEvmxRty
cleos create account eosio dan EOS5apmi5ksicQydemG6rCT9XVt6ToRpQLWCZeMBiHXVrmEvmxRty
cleos set contract chess ~/contracts/eos-chess/ chess.wasm chess.abi -p chess@active
