cleos create account eosio bob EOS7weWsuUWPrFBEibskFmtdSisvtAg1ggUGqN13tNXP9WsfhgmcR 
cleos create account eosio alice EOS7weWsuUWPrFBEibskFmtdSisvtAg1ggUGqN13tNXP9WsfhgmcR
cleos create account eosio chess EOS7weWsuUWPrFBEibskFmtdSisvtAg1ggUGqN13tNXP9WsfhgmcR 
cleos create account eosio dan EOS7weWsuUWPrFBEibskFmtdSisvtAg1ggUGqN13tNXP9WsfhgmcR 
cleos set contract chess /Users/jslater/contracts/chess/ -p chess@active
