cleos push action chess move '["alice", "0", "11", "28", "0"]' -p alice@active
cleos push action chess move '["bob", "0", "27", "36", "0"]' -p bob@active
cleos push action chess move '["alice", "0", "4", "19", "0"]' -p alice@active
cleos push action chess move '["bob", "0", "21", "46", "0"]' -p bob@active
cleos push action chess move '["alice", "0", "2", "39", "0"]' -p alice@active
cleos push action chess move '["bob", "0", "31", "48", "0"]' -p bob@active
cleos push action chess move '["alice", "0", "2", "32", "0"]' -p alice@active
cleos push action chess move '["bob", "0", "20", "43", "0"]' -p bob@active
cleos push action chess move '["alice", "0", "0", "2", "0"]' -p alice@active
cleos push action chess move '["bob", "0", "18", "52", "0"]' -p bob@active
cleos push action chess move '["alice", "0", "6", "4", "0"]' -p alice@active
cleos push action chess move '["bob", "0", "30", "39", "0"]' -p bob@active
cleos push action chess move '["alice", "0", "2", "23", "0"]' -p alice@active
cleos push action chess move '["bob", "0", "28", "45", "0"]' -p bob@active
cleos push action chess move '["alice", "0", "13", "22", "0"]' -p alice@active
cleos push action chess move '["bob", "0", "16", "58", "0"]' -p bob@active
cleos push action chess move '["alice", "0", "8", "17", "0"]' -p alice@active
cleos push action chess move '["bob", "0", "21", "63", "0"]' -p bob@active
cleos push action chess move '["alice", "0", "12", "29", "0"]' -p alice@active
cleos push action chess move '["bob", "0", "21", "53", "0"]' -p bob@active
cleos push action chess move '["alice", "0", "13", "30", "0"]' -p alice@active
cleos push action chess move '["bob", "0", "29", "46", "0"]' -p bob@active
cleos push action chess move '["alice", "0", "13", "39", "0"]' -p alice@active
cleos push action chess move '["bob", "0", "31", "39", "0"]' -p bob@active
cleos push action chess move '["alice", "0", "5", "22", "0"]' -p alice@active
cleos push action chess move '["bob", "0", "19", "55", "0"]' -p bob@active
cleos push action chess move '["alice", "0", "3", "34", "0"]' -p alice@active
cleos push action chess move '["bob", "0", "31", "31", "0"]' -p bob@active
cleos push action chess move '["alice", "0", "5", "7", "0"]' -p alice@active
cleos push action chess move '["bob", "0", "24", "41", "0"]' -p bob@active
cleos push action chess move '["alice", "0", "3", "25", "0"]' -p alice@active
cleos push action chess move '["bob", "0", "29", "38", "0"]' -p bob@active
cleos push action chess move '["alice", "0", "12", "36", "0"]' -p alice@active
cleos push action chess move '["bob", "0", "20", "28", "0"]' -p bob@active
cleos push action chess move '["alice", "0", "3", "52", "0"]' -p alice@active
cleos push action chess move '["bob", "0", "17", "52", "0"]' -p bob@active
cleos push action chess move '["alice", "0", "12", "45", "0"]' -p alice@active
cleos push action chess move '["bob", "0", "17", "43", "0"]' -p bob@active
cleos push action chess move '["alice", "0", "5", "13", "0"]' -p alice@active
cleos push action chess move '["bob", "0", "20", "45", "0"]' -p bob@active
cleos push action chess move '["alice", "0", "5", "30", "0"]' -p alice@active
cleos push action chess move '["bob", "0", "20", "30", "0"]' -p bob@active
cleos push action chess move '["alice", "0", "2", "30", "0"]' -p alice@active
cleos push action chess move '["bob", "0", "21", "47", "0"]' -p bob@active
cleos push action chess move '["alice", "0", "4", "36", "0"]' -p alice@active
cleos push action chess move '["bob", "0", "23", "60", "0"]' -p bob@active
cleos push action chess move '["alice", "0", "2", "51", "0"]' -p alice@active
cleos push action chess move '["bob", "0", "22", "51", "0"]' -p bob@active
cleos push action chess move '["alice", "0", "4", "51", "0"]' -p alice@active
cleos push action chess move '["bob", "0", "23", "4", "0"]' -p bob@active
cleos push action chess move '["alice", "0", "1", "4", "0"]' -p alice@active
cleos push action chess move '["bob", "0", "16", "51", "0"]' -p bob@active
cleos push action chess move '["alice", "0", "1", "20", "0"]' -p alice@active
cleos push action chess move '["bob", "0", "17", "34", "0"]' -p bob@active
cleos push action chess move '["alice", "0", "1", "34", "0"]' -p alice@active
cleos push action chess move '["bob", "0", "24", "34", "0"]' -p bob@active
cleos push action chess move '["alice", "0", "14", "23", "0"]' -p alice@active
cleos push action chess move '["bob", "0", "16", "44", "0"]' -p bob@active
cleos push action chess move '["alice", "0", "15", "24", "0"]' -p alice@active
cleos push action chess move '["bob", "0", "16", "45", "0"]' -p bob@active
cleos push action chess move '["alice", "0", "15", "31", "0"]' -p alice@active
cleos push action chess move '["bob", "0", "29", "31", "0"]' -p bob@active
cleos push action chess move '["alice", "0", "7", "40", "0"]' -p alice@active
cleos push action chess move '["bob", "0", "21", "37", "0"]' -p bob@active
cleos push action chess move '["alice", "0", "10", "19", "0"]' -p alice@active
cleos push action chess move '["bob", "0", "19", "62", "0"]' -p bob@active
cleos push action chess move '["alice", "0", "0", "11", "0"]' -p alice@active
cleos push action chess move '["bob", "0", "19", "35", "0"]' -p bob@active
cleos push action chess move '["alice", "0", "7", "56", "0"]' -p alice@active
cleos push action chess move '["bob", "0", "25", "42", "0"]' -p bob@active
cleos push action chess move '["alice", "0", "7", "48", "0"]' -p alice@active
cleos push action chess move '["bob", "0", "16", "38", "0"]' -p bob@active
cleos push action chess move '["alice", "0", "0", "4", "0"]' -p alice@active
cleos push action chess move '["bob", "0", "21", "27", "0"]' -p bob@active
cleos push action chess move '["alice", "0", "9", "18", "0"]' -p alice@active
cleos push action chess move '["bob", "0", "21", "17", "0"]' -p bob@active
cleos push action chess move '["alice", "0", "0", "13", "0"]' -p alice@active
cleos push action chess move '["bob", "0", "16", "39", "0"]' -p bob@active
cleos push action chess move '["alice", "0", "7", "45", "0"]' -p alice@active
cleos push action chess move '["bob", "0", "16", "38", "0"]' -p bob@active
cleos push action chess move '["alice", "0", "7", "48", "0"]' -p alice@active
cleos push action chess move '["bob", "0", "21", "11", "0"]' -p bob@active
cleos push action chess move '["alice", "0", "9", "26", "0"]' -p alice@active
cleos push action chess move '["bob", "0", "19", "21", "0"]' -p bob@active
cleos push action chess move '["alice", "0", "7", "44", "0"]' -p alice@active
